import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { DashboardData } from '../types';

const tooltipStyle = { background: '#0c1510', border: '1px solid #254b32', borderRadius: 10, color: '#e8f4eb', fontSize: 12 };

export function DashboardCharts({ data }: { data: DashboardData }) {
  return <div className="dashboard-charts"><article className="chart-card chart-wide"><div className="card-heading"><div><p className="eyebrow">Transaction monitoring</p><h2>Transaction volume</h2></div><span className="chart-legend"><i /> Total &nbsp; <i className="legend-alert" /> Suspicious</span></div><ResponsiveContainer width="100%" height={240}><AreaChart data={data.timeline}><defs><linearGradient id="volume" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#1cc86a" stopOpacity={.34} /><stop offset="100%" stopColor="#1cc86a" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="label" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} width={35} /><Tooltip contentStyle={tooltipStyle} /><Area dataKey="total" type="monotone" stroke="#1cc86a" strokeWidth={2} fill="url(#volume)" /><Area dataKey="suspicious" type="monotone" stroke="#d8793f" strokeWidth={2} fill="none" /></AreaChart></ResponsiveContainer></article>
    <article className="chart-card"><div className="card-heading"><div><p className="eyebrow">Exposure profile</p><h2>Risk distribution</h2></div></div><div className="donut-chart"><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={data.riskDistribution} dataKey="value" innerRadius={59} outerRadius={80} paddingAngle={3}>{data.riskDistribution.map((slice) => <Cell key={slice.name} fill={slice.color} />)}</Pie><Tooltip contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer><div className="donut-center"><b>1,276</b><span>Flagged</span></div></div><div className="risk-legend">{data.riskDistribution.map((slice) => <span key={slice.name}><i style={{ background: slice.color }} />{slice.name} <b>{slice.value}%</b></span>)}</div></article>
    <article className="chart-card chart-wide"><div className="card-heading"><div><p className="eyebrow">Processing overview</p><h2>Transaction status distribution</h2></div></div><ResponsiveContainer width="100%" height={218}><BarChart data={data.statusDistribution} layout="vertical" margin={{ left: 15 }}><XAxis type="number" hide /><YAxis dataKey="name" type="category" axisLine={false} tickLine={false} width={70} /><Tooltip contentStyle={tooltipStyle} cursor={{ fill: '#ffffff08' }} /><Bar dataKey="value" radius={[0, 6, 6, 0]} barSize={18}>{data.statusDistribution.map((slice) => <Cell key={slice.name} fill={slice.color} />)}</Bar></BarChart></ResponsiveContainer></article>
  </div>;
}
