import { Check, Download, FileDown, FileText, LoaderCircle, ShieldCheck, TableProperties } from 'lucide-react';
import { useState } from 'react';
import { useGenerateReport } from '../hooks';
import type { ReportSection } from '../types';

const reportSections: { title: ReportSection; description: string }[] = [
  { title: 'Investigation Summary', description: 'Case context, priority and lead investigator.' }, { title: 'Transaction Summary', description: 'Material transfers, pathways and counterparties.' }, { title: 'Risk Analysis', description: 'Risk scoring rationale and triggered indicators.' }, { title: 'Network Findings', description: 'Entity links, clusters and money-flow relationships.' }, { title: 'Evidence', description: 'Attached records, notes and supporting artifacts.' }, { title: 'Timeline', description: 'Chronological record of case events and actions.' },
];

export function ReportsPage() {
  const [selected, setSelected] = useState<ReportSection[]>(reportSections.map((section) => section.title)); const report = useGenerateReport();
  const toggle = (section: ReportSection) => setSelected((current) => current.includes(section) ? current.filter((item) => item !== section) : [...current, section]);
  async function generate() { await report.mutateAsync({ title: 'Operation Emerald Trace — Investigation Report', caseId: 'INV-2026-041', sections: selected, classification: 'Restricted' }); }
  return <div className="page-container"><div className="page-heading"><div><p className="eyebrow">Evidence synthesis</p><h1>Report Center</h1><p>Build a structured, export-ready record of investigation findings.</p></div><div className="classification"><ShieldCheck size={16} /> Restricted · Investigator use</div></div><div className="report-layout"><section className="content-card report-builder"><div className="card-heading"><div><p className="eyebrow">Report configuration</p><h2>Operation Emerald Trace</h2><p>Case INV-2026-041</p></div><span className="report-draft">Draft</span></div><label className="form-field"><span>Report title</span><input defaultValue="Operation Emerald Trace — Investigation Report" /></label><div className="report-section-heading"><div><h3>Include sections</h3><p>Select the intelligence elements to include in the final report.</p></div><span>{selected.length} / {reportSections.length} selected</span></div><div className="report-sections">{reportSections.map((section) => <label className="report-section" key={section.title}><input type="checkbox" checked={selected.includes(section.title)} onChange={() => toggle(section.title)} /><span className="section-check"><Check size={14} /></span><div><b>{section.title}</b><p>{section.description}</p></div></label>)}</div><div className="report-actions"><button className="button button-primary" onClick={() => void generate()} disabled={report.isPending}>{report.isPending ? <><LoaderCircle className="spin" size={16} /> Generating...</> : <><FileText size={16} /> Generate Report</>}</button>{report.isSuccess && <span className="success-note"><Check size={15} /> Draft {report.data.reportId} generated</span>}</div></section><aside className="report-aside"><article className="content-card report-preview"><div className="report-paper"><div className="paper-top"><ShieldCheck size={21} /><span>CONFIDENTIAL</span></div><p>FINANCIAL INTELLIGENCE</p><h2>Investigation Report</h2><strong>Operation Emerald Trace</strong><hr /><div><small>CASE REFERENCE</small><b>INV-2026-041</b></div><div><small>PREPARED FOR</small><b>Investigation Center</b></div><div><small>GENERATED ON</small><b>27 August 2026</b></div><footer>Restricted circulation only</footer></div></article><article className="content-card export-card"><div><FileDown size={20} /><div><h3>Export options</h3><p>Available after generation</p></div></div><button className="button button-secondary full-width" disabled={!report.isSuccess}><Download size={15} /> Export PDF</button><button className="button button-secondary full-width" disabled={!report.isSuccess}><TableProperties size={15} /> Export CSV</button></article></aside></div></div>;
}
