import { AlertTriangle, CheckCheck, ChevronRight, Filter, ShieldAlert } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ErrorState, LoadingState } from '../../../shared/components/States';
import { StatusPill } from '../../../shared/components/StatusPill';
import { useAlerts } from '../hooks';

export function AlertsPage() {
  const { data, isLoading, isError, refetch } = useAlerts(); const [severity, setSeverity] = useState('all'); const navigate = useNavigate();
  if (isLoading) return <LoadingState label="Checking security alerts..." />; if (isError || !data) return <ErrorState message="Unable to load risk alerts." onRetry={() => void refetch()} />;
  const alerts = data.items.filter((alert) => severity === 'all' || alert.severity === severity);
  return <div className="page-container"><div className="page-heading"><div><p className="eyebrow">Security monitoring</p><h1>Risk Alerts</h1><p>Prioritized signals that need an investigator’s attention.</p></div><button className="button button-secondary"><CheckCheck size={16} /> Mark all reviewed</button></div><div className="alert-summary"><div><span className="summary-icon critical"><ShieldAlert size={18} /></span><div><b>{data.items.filter((item) => item.severity === 'critical').length}</b><p>Critical alerts</p></div></div><div><span className="summary-icon high"><AlertTriangle size={18} /></span><div><b>{data.items.filter((item) => item.severity === 'high').length}</b><p>High priority</p></div></div><div><span className="summary-icon neutral"><CheckCheck size={18} /></span><div><b>{data.items.filter((item) => item.status === 'resolved').length}</b><p>Resolved today</p></div></div></div><section className="content-card alert-list-card"><div className="table-toolbar"><div><h2>Active signals</h2><p>System-generated detection rules and investigation triggers</p></div><div className="alert-filters"><Filter size={15} /><select value={severity} onChange={(e) => setSeverity(e.target.value)} aria-label="Filter alerts by severity"><option value="all">All severity</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div></div><div className="alert-list">{alerts.map((alert) => <article className={`alert-row alert-${alert.severity}`} key={alert.id}><span className="alert-severity-icon"><AlertTriangle size={18} /></span><div className="alert-main"><div><span className="alert-id">{alert.id}</span><StatusPill status={alert.severity} /><StatusPill status={alert.status} /></div><h3>{alert.entity}</h3><p>{alert.reason}</p><small>Transaction <button onClick={() => navigate(`/transactions/${alert.transactionId}`)}>{alert.transactionId}</button> · {alert.timestamp}</small></div><button className="row-action" onClick={() => navigate(`/transactions/${alert.transactionId}`)} aria-label={`Inspect ${alert.id}`}><ChevronRight size={19} /></button></article>)}</div></section></div>;
}
