from abc import ABC, abstractmethod
from app.schemas.models import Account, Transaction, Network, Investigation

class AccountRepository(ABC):
    @abstractmethod
    def list(self)->list[Account]: ...
    @abstractmethod
    def get(self, entity_id:str)->Account|None: ...
class TransactionRepository(ABC):
    @abstractmethod
    def list(self)->list[Transaction]: ...
    @abstractmethod
    def get(self, entity_id:str)->Transaction|None: ...
    @abstractmethod
    def add(self, entity:Transaction)->Transaction: ...
class NetworkRepository(ABC):
    @abstractmethod
    def list(self)->list[Network]: ...
    @abstractmethod
    def get(self, entity_id:str)->Network|None: ...
class InvestigationRepository(ABC):
    @abstractmethod
    def list(self)->list[Investigation]: ...
    @abstractmethod
    def get(self, entity_id:str)->Investigation|None: ...
    @abstractmethod
    def add(self, entity:Investigation)->Investigation: ...
    @abstractmethod
    def update(self, entity:Investigation)->Investigation: ...
